apiVersion: v1
kind: Service
metadata:
  name: academyapp-service
spec:
  ports:
    - port: 80
      targetPort: academyapp-port
      protocol: TCP
  selector:
    app: academyapp
  type: LoadBalancer
